# -*- coding: utf-8 -*-
"""Lab Assignement.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gaSepN3kCQlKtw0pdZAlaHIrR_-52SDc

*Srivaths Iyer_
E division_
Roll No_520*
"""

def avgpck(name):
  average=0
  for i in range(len(data4)):
    if data4[i][4]==name:
      average=average+float(data4[i][6])
  Average=average/3
  print("Average package of ", name ,"is",Average)

import csv
f1=open("/content/stud_info.csv","r")
f2=open("/content/stud_placement.csv","r")
f3=open("/content/student_marks.csv","r")
data1=list(csv.reader(f1))
print(data1)
data2=list(csv.reader(f2))
i=0
while i < 11:
    del data2[i][0]
    i+=1
print(data2)

data3=list(csv.reader(f3))
i=0
while i < 11:
    del data3[i][0]
    i+=1
print(data3)
data4=[]
for i in range(len(data1)):
  data4.append(data1[i]+data2[i]+data3[i])
print(data4)
f4 = open("StudentDetails.csv", "w")
cw=csv.writer(f4)
cw.writerows(data4)
RollNo=[]
Name=[]
Gender=[]
Maths=[]
Company=[]
JobRole=[]
package=[]
Total=[]
i=1
while i<11:
  RollNo.append(data4[i][0])
  Name.append(data4[i][1])
  Gender.append(data4[i][2])
  Company.append(data4[i][4])
  JobRole.append(data4[i][5])
  package.append(data4[i][6])
  Maths.append(data4[i][7])
  Total.append(data4[i][10])
  i+=1
print(RollNo,Name,Gender,Company,JobRole,package,Total)
maths=[]
for i in range(len(package)):
  maths.append(float(Maths[i]))
print(maths)
avgpck("TCS")
avgpck("Infosys")
avgpck("Oracle")
avgpck("Mindtree")
print("Maximum marks obtained in the college is",max(Total))
print("Topper of college is",Name[Total.index(max(Total))])
Package=[]
for i in range(len(package)):
  Package.append(float(package[i]))
print(Package)
print("Minimum package of the company",Company[Package.index(min(Package))],"is",Package[Package.index(min(Package))])
count=0
for i in range(len(Company)):
  if Company[i]=="TCS":
    count=count+1
print(count)
print("Total marks in maths subject obtained by the whole class out of 1000 is",sum(maths),"and its percentage is",(sum(maths)/1000)*100,"%")
f1.close()
f2.close()
f3.close()
f4.close()