# -*- coding: utf-8 -*-
"""Lab Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQ2S4lSsXRsIjm7EetUr3ztNPzp-dl3s
"""

import csv
import statistics
f1=open("/content/Sales.csv","r")
data1=list(csv.reader(f1))
print(data1)
prodetails=[]
for i in range(len(data1)):
  prodetails.append(data1[i][1])
print(prodetails)
ID=[]
for i in range(len(data1)):
  ID.append(data1[i][0])
print(ID)
suppdetails=[]
for i in range(len(data1)):
  suppdetails.append(data1[i][2])
SuppDetails={}
for i in range(1,len(data1)):
  SuppDetails.update({ID[i]:suppdetails[i]})
print(SuppDetails)
CustDetails=[]
for i in range(1,len(data1)):
  CustDetails.append(data1[i][3])
print(tuple(CustDetails))
gender=[]
for i in range(len(data1)):
  gender.append(data1[i][4])
print(gender)
for i in range(len(data1)):
  prodetails.append(data1[i][1])
print(prodetails)
suppdetails=list(SuppDetails.values())
print("The most popular product for sales is",statistics.mode(prodetails))
print("The best supplier for sales is",statistics.mode(suppdetails))
CustDet=list(CustDetails)
print(CustDet)
print("The customer who buys most of the product is",statistics.mode(CustDet))
count=0
for i in range(len(gender)):
  if gender[i]== "Female":
    count+=1
print("The Number of customers who are female are",count)

