# -*- coding: utf-8 -*-
"""LabAssignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdCtzhFg2Srr-kE_LUEOyWFuzfOMHgPK
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
data=pd.read_csv("/content/tips.csv")
df=pd.DataFrame(data)
print(df)

"""Histogram of total bill amounts"""

plt.hist(df['total_bill'])
plt.xlabel('Total Bill')
plt.ylabel('Frequency')
plt.title('Histogram of Total Bill Amounts')
plt.show()

"""Bar plot of the average tip by day


"""

avg_tip_by_day = df.groupby('day')['tip'].mean()
plt.bar(avg_tip_by_day.index, avg_tip_by_day)
plt.xlabel('Day')
plt.ylabel('Average Tip')
plt.title('Average Tip by Day')
plt.show()

"""Scatter plot of total bill vs. tip"""

plt.scatter(df['total_bill'], df['tip'])
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.title('Total Bill vs. Tip')
plt.show()

"""Pie chart of the distribution of genders"""

gender_counts = df['sex'].value_counts()
plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%')
plt.title('Distribution of Genders')
plt.show()

"""Box plot of total bill by smoker status"""

plt.boxplot([df[df['smoker'] == 'Yes']['total_bill'], df[df['smoker'] == 'No']['total_bill']], labels=['Smoker', 'Non-Smoker'])
plt.ylabel('Total Bill')
plt.title('Total Bill by Smoker Status')
plt.show()

"""Violin plot of total bill by day and time"""

import seaborn as sns
sns.violinplot(data=df, x='day', y='total_bill', hue='time')

"""Heatmap of the correlation matrix between numerical columns"""

numeric_columns = ['total_bill', 'tip', 'size']
correlation_matrix = df[numeric_columns].corr()
sns.heatmap(data=correlation_matrix, annot=True, cmap='coolwarm')

"""Swarm plot of total bill by day and smoker status"""

sns.swarmplot(data=df, x='day', y='total_bill', hue='smoker')

"""Line plot of the cumulative sum of total bill by party size"""

cumulative_total_bill = df.groupby('size')['total_bill'].cumsum()
df['cumulative_total_bill'] = cumulative_total_bill
sns.lineplot(data=df, x='size', y='cumulative_total_bill')

"""Pairplot of numerical columns with hue based on smoker status"""

numeric_columns = ['total_bill', 'tip', 'size']
sns.set(style="ticks")
sns.pairplot(data=df, vars=numeric_columns, hue='smoker', kind='scatter')

"""Box Plot of tip amount by party size"""

import matplotlib.pyplot as plt

sns.boxplot(x='size', y='tip', data=data)
plt.xlabel('Party Size')
plt.ylabel('Tip Amount')
plt.title('Distribution of Tip Amounts by Party Size')
plt.show()

